# Generated by Django 5.1.4 on 2025-01-14 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_groups', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
