# Generated by Django 5.1.4 on 2025-01-21 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0008_remove_expense_group_id_alter_expense_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.group'),
            preserve_default=False,
        ),
    ]
