# Generated by Django 5.1.4 on 2025-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0011_alter_expense_split_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
