# Generated by Django 5.1.4 on 2025-03-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0012_alter_settlement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='settlement_date',
            field=models.DateField(default='2024-03-09'),
        ),
    ]
