# Generated by Django 5.1.4 on 2025-03-16 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0013_settlement_settlement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='settlement_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
