# Generated by Django 5.1.4 on 2025-07-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0014_alter_settlement_settlement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Rent', 'Rent'), ('Groceries', 'Groceries'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Medical', 'Medical'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Others', 'Others')], max_length=100, unique=True),
        ),
    ]
