# Generated by Django 5.1.4 on 2025-01-13 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_alter_customuser_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='id',
            new_name='group_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
