# Generated by Django 5.1.4 on 2025-01-14 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_rename_id_group_group_id_expense_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='%(class)s_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
