# Generated by Django 5.1.4 on 2025-01-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_settlement_amount_alter_customuser_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_groups', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
