--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Homebrew)
-- Dumped by pg_dump version 17.0

-- Started on 2026-04-13 00:55:13 EDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 17323)
-- Name: expense_tracker_customuser; Type: TABLE; Schema: public; Owner: rachitpandya
--

CREATE TABLE public.expense_tracker_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    college character varying(255) NOT NULL,
    semester integer NOT NULL,
    default_payment_methods character varying(255) NOT NULL,
    is_verified boolean NOT NULL,
    jwt_token character varying(1024),
    verification_code character varying(6),
    verification_code_created_at timestamp with time zone
);


ALTER TABLE public.expense_tracker_customuser OWNER TO rachitpandya;

--
-- TOC entry 221 (class 1259 OID 17322)
-- Name: expense_tracker_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: rachitpandya
--

ALTER TABLE public.expense_tracker_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_tracker_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3713 (class 0 OID 17323)
-- Dependencies: 222
-- Data for Name: expense_tracker_customuser; Type: TABLE DATA; Schema: public; Owner: rachitpandya
--

COPY public.expense_tracker_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, college, semester, default_payment_methods, is_verified, jwt_token, verification_code, verification_code_created_at) FROM stdin;
11	pbkdf2_sha256$870000$hG9zs7XXCZq4BzjoynqBw7$S7MU3MdjLnTCANMsuKbfl7GxeDpnYM4nHYyv28wnfi0=	\N	f	newuser			new@example.com	f	t	2025-08-07 23:27:16.271745-04	Test College	3	Cash	f	\N	811014	2025-08-07 23:28:46.296751-04
16	pbkdf2_sha256$870000$tPfay4IOhzM1VxR4A5tyjR$8V6SphTtjDKiEfPmKCjYZz2PFR2FkXCWIB0NcPA+WJ0=	2026-04-13 00:47:00.956928-04	t	admin			pandyarachit1525@gmail.com	t	t	2026-04-13 00:44:32.767574-04	Centennial College	3	Net Banking	t	\N	\N	\N
12	pbkdf2_sha256$870000$RgySJZNoWVFFUycxm7imVV$voB4sSGPVr/wjY52GysJfGYm/RPEDNqMlpKnA6JdzmI=	2025-08-16 00:31:36.069674-04	f	newuser1			new1@example.com	f	t	2025-08-07 23:38:03.93527-04	Test College	3	Cash	t	\N	368182	2025-08-07 23:38:42.982712-04
\.


--
-- TOC entry 3719 (class 0 OID 0)
-- Dependencies: 221
-- Name: expense_tracker_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rachitpandya
--

SELECT pg_catalog.setval('public.expense_tracker_customuser_id_seq', 16, true);


--
-- TOC entry 3569 (class 2606 OID 17329)
-- Name: expense_tracker_customuser expense_tracker_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: rachitpandya
--

ALTER TABLE ONLY public.expense_tracker_customuser
    ADD CONSTRAINT expense_tracker_customuser_pkey PRIMARY KEY (id);


--
-- TOC entry 3572 (class 2606 OID 17331)
-- Name: expense_tracker_customuser expense_tracker_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: rachitpandya
--

ALTER TABLE ONLY public.expense_tracker_customuser
    ADD CONSTRAINT expense_tracker_customuser_username_key UNIQUE (username);


--
-- TOC entry 3570 (class 1259 OID 17369)
-- Name: expense_tracker_customuser_username_9eb660ef_like; Type: INDEX; Schema: public; Owner: rachitpandya
--

CREATE INDEX expense_tracker_customuser_username_9eb660ef_like ON public.expense_tracker_customuser USING btree (username varchar_pattern_ops);


-- Completed on 2026-04-13 00:55:13 EDT

--
-- PostgreSQL database dump complete
--

