# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestResendcode():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_resendcode(self):
    # Test name: Resend_code
    # Step # | name | target | value
    # 1 | open | http://localhost:3000/resend | 
    self.driver.get("http://localhost:3000/resend")
    # 2 | setWindowSize | 983x844 | 
    self.driver.set_window_size(983, 844)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | pandyarachit1525@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("pandyarachit1525@gmail.com")
    # 5 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
