# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInvalidcreds():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_invalidcreds(self):
    # Test name: invalid_creds
    # Step # | name | target | value
    # 1 | open | http://localhost:3000/ | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 983x844 | 
    self.driver.set_window_size(983, 844)
    # 3 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 4 | type | name=username | rachit
    self.driver.find_element(By.NAME, "username").send_keys("rachit")
    # 5 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 6 | type | name=password | abcd
    self.driver.find_element(By.NAME, "password").send_keys("abcd")
    # 7 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 8 | assertText | css=div > p:nth-child(2) | Invalid username or password.
    assert self.driver.find_element(By.CSS_SELECTOR, "div > p:nth-child(2)").text == "Invalid username or password."
  
