# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignuptest():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signuptest(self):
    # Test name: Signup_test
    # Step # | name | target | value
    # 1 | store | testuser1 | username1
    self.vars["username1"] = "testuser1"
    # 2 | store | Test@123 | password1
    self.vars["password1"] = "Test@123"
    # 3 | store | Test@123 | password2
    self.vars["password2"] = "Test@123"
    # 4 | open | http://localhost:3000/ | 
    self.driver.get("http://localhost:3000/")
    # 5 | click | linkText=Sign up | 
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    # 6 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 7 | type | name=username | ${username1}
    self.driver.find_element(By.NAME, "username").send_keys(self.vars["username1"])
    # 8 | click | name=email | 
    self.driver.find_element(By.NAME, "email").click()
    # 9 | type | name=email | pandyarachit1525@gmail.com
    self.driver.find_element(By.NAME, "email").send_keys("pandyarachit1525@gmail.com")
    # 10 | click | name=password1 | 
    self.driver.find_element(By.NAME, "password1").click()
    # 11 | type | name=password1 | ${password1}
    self.driver.find_element(By.NAME, "password1").send_keys(self.vars["password1"])
    # 12 | click | name=password2 | 
    self.driver.find_element(By.NAME, "password2").click()
    # 13 | type | name=password2 | ${password2}
    self.driver.find_element(By.NAME, "password2").send_keys(self.vars["password2"])
    # 14 | click | name=college | 
    self.driver.find_element(By.NAME, "college").click()
    # 15 | type | name=college | Loyalist College
    self.driver.find_element(By.NAME, "college").send_keys("Loyalist College")
    # 16 | click | css=form | 
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    # 17 | click | name=semester | 
    self.driver.find_element(By.NAME, "semester").click()
    # 18 | type | name=semester | 3
    self.driver.find_element(By.NAME, "semester").send_keys("3")
    # 19 | click | name=default_payment_method | 
    self.driver.find_element(By.NAME, "default_payment_method").click()
    # 20 | type | name=default_payment_method | UPI
    self.driver.find_element(By.NAME, "default_payment_method").send_keys("UPI")
    # 21 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
